# Generated by Django 4.0 on 2021-12-15 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data_view',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ident', models.IntegerField()),
                ('id_lot', models.TextField()),
                ('nb_piece', models.IntegerField()),
                ('typologie', models.TextField()),
                ('prix_tva_reduite', models.FloatField()),
                ('prix_tva_normale', models.FloatField()),
                ('prix_HT', models.FloatField()),
                ('prix_m2_HT', models.FloatField()),
                ('prix_m2_TTC', models.FloatField()),
                ('surface', models.FloatField()),
                ('etage', models.IntegerField()),
                ('orientation', models.TextField()),
                ('exterieur', models.BooleanField()),
                ('balcony', models.BooleanField()),
                ('garden', models.BooleanField()),
                ('parking', models.FloatField()),
                ('nom_programme', models.TextField()),
                ('ville', models.TextField()),
                ('departement', models.FloatField()),
                ('date_fin_programme', models.TextField()),
                ('adresse_entiere', models.TextField()),
                ('promoteur', models.TextField()),
                ('date_extraction', models.TextField()),
            ],
        ),
    ]
