# Generated by Django 4.0 on 2021-12-16 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_view', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data_view',
            name='ident',
        ),
    ]
